hackathon:
  greebox:
    info:
      team-name: Brainbox Ninjas
      project-name: Nagarro Green Campus

premise:
  info:
    name: Nagarro Campus
    totalFloors: 4
    floorDetails:
      - 
        sectionName: Floor1
        capacity: 100
        controller: 2
      - 
        sectionName: Floor2
        capacity: 80
        controller: 2
      - 
        sectionName: Floor3
        capacity: 110
        controller: 2
      - 
        sectionName: Floor4
        capacity: 60
        controller: 1


